name: Example Workflow
on:
  workflow_dispatch:
    inputs:
      person:
        description: "Person's name"
        required: true
        default: "Anon"

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting
        run: |
          echo "Hello Martin. I am ${{ github.event.inputs.person }}"
